# config docker-compose de shomgt3 pour test sur VPS OVH - 31/5/2022
# fichier dans /Users/benoit/Sites/geoapi/shomgt3
# lance 2 containers:
#   - shomgt expose les GéoTiffs
#   - sgupdt construit les données par téléchargement à partir du serveur de cartes 7z
# Les 2 conteneurs partagent le volume sg3data dans lequel sgupdt construit les données et shomgt les consomme

version: '3'
services:
  shomgt:
    image: benoitdavid/shomgt3:shomgt-v0.3
    hostname: shomgt
    ports: ["80:80"]
    volumes:
      - sg3data:/var/www/data
  sgupdt:
    image: benoitdavid/shomgt3:sgupdt-v0.3
    hostname: sgupdt
    volumes:
      - sg3data:/var/www/data
volumes:
  sg3data:
