# config docker-compose de shomgt3 pour test sur VPS OVH - 23/5/2022
# fichier dans /Users/benoit/Sites/geoapi/shomgt3
# lance 2 containers:
#   - shomgt expose les GéoTiffs
#   - sgupdt construit les données par téléchargement à partir du serveur de cartes 7z
# Les 2 conteneurs partagent le volume sg3data dans lequel sgupdt construit les données et shomgt les consomme

version: '3'
services:
  shomgt:
    image: benoitdavid/shomgt3:shomgt-v0.3
    hostname: shomgt
    #ports: ["80:80"]
    expose: [80]
    volumes:
      - sg3data:/var/www/data
    environment:
      # SHOMGT3_MAPS_DIR_PATH: /var/www/data/maps # répertoire dans lequel lire les cartes expansées
      SHOMGT3_MAPWCAT_FORCE_HTTPS: 'true' # force mapwcat à générer des URL https
    networks:
      - registre_default
    labels:
      - traefik.http.routers.shomgt.rule=Host(`shomgt3.ecolabdata.fr`)
      - traefik.http.routers.shomgt.tls=true
      - traefik.http.routers.shomgt.tls.certresolver=myresolver
  sgupdt:
    image: benoitdavid/shomgt3:sgupdt-v0.3
    hostname: sgupdt
    volumes:
      - sg3data:/var/www/data
    environment:
      # SHOMGT3_MAPS_DIR_PATH: /var/www/data/maps # répertoire dans lequel écrire les cartes expansées
      SHOMGT3_SERVER_URL: http://bd:test@sgserver.geoapi.fr/index.php # url du serveur de cartes 7z
    networks:
      - registre_default
volumes:
  sg3data:
networks:
  registre_default:
    external: true
