# config docker-compose de shomgt3 pour test sur VPS OVH - 10/6/2022
# fichier dans /Users/benoit/Sites/geoapi/shomgt3
# lance 2 containers:
#   - shomgt expose les GéoTiffs
#   - sgupdt construit les données par téléchargement à partir du serveur de cartes 7z
# Les 2 conteneurs partagent le volume sg3data dans lequel sgupdt construit les données et shomgt les consomme

version: '3'
services:
  shomgt:
    image: benoitdavid/shomgt3:shomgt-v0.6
    hostname: shomgt
    ports: ["80:80"]
    volumes:
      - sg3data:/var/www/data
  sgupdt:
    image: benoitdavid/shomgt3:sgupdt-v0.6
    hostname: sgupdt
    volumes:
      - sg3data:/var/www/data
    #environment:
    #  SHOMGT3_SERVER_URL: https://{login}:{passwd}@php81/geoapi/shomgt3/sgserver/index.php # url du serveur de cartes
    #  HTTP_PROXY: http://100.78.40.201:8080/
    #  HTTPS_PROXY: http://100.78.40.201:8080/
    #  http_proxy: http://100.78.40.201:8080/
    #  https_proxy: http://100.78.40.201:8080/
volumes:
  sg3data:
